### ISSUE TITLE
track retainer's gil and more

### ISSUE THREAD

**Issue by FairyScript** [AtmoOmen/CurrencyTracker#10]
In the current version, only the character's own gil can be tracked. Can it support recording retainers' gil (selling log and more)?

**Comment by AtmoOmen** [comment]
I will consider including counting retainers' currencies amount in the future.
As for selling history, there should be another plugin to do that and I think that feature may be hard to integrate into current display mode.

Thanks for suggestions!

**Comment by AtmoOmen** [comment]
Glad to inform that the latest version 1.3.2.4 now includes basic support for tracking currencies in retainers, saddle bags, and premium saddle bags.
