### ISSUE TITLE
[Issue] CurrencyTracker no longer parsing data in data folder, only when changing characters and writes to the wrong character

### ISSUE THREAD

**Issue by Sinpls** [AtmoOmen/CurrencyTracker#11]
Since the latest update of 14/10 CurrencyTracker has not been writing any data to the .txt files in the data folder on all my characters but one.
I use the plugin to track multiple characters, but now it only writes to character 1 and upon login to character 2 it writes the values to the .txt file of character 1 and then stops working. It does show correctly in the plugin window itself until you restart the plugin, then the data is gone.
This issue occurs for almost all tracked currencies.
Deleting the .txt files also does not help. It only regenerates them for 1 character and then the same issue occurs
Below are the latest logs in character 1, this character is always in Mist. Some of my other characters are always in The Goblet.

2023/10/18 13:35:45;10312115;9383674;Mist;
2023/10/18 14:06:31;993828;-9318287;Mist;
2023/10/18 14:20:24;10312115;9318287;Mist;
2023/10/18 14:23:04;1375792;-8936323;The Goblet;
2023/10/18 14:24:33;2067753;691961;The Goblet;
2023/10/18 14:27:41;1224635;-843118;Mist;
2023/10/18 14:28:38;1174627;-50008;The Goblet;
2023/10/18 14:29:58;413266;-761361;The Goblet;
2023/10/18 14:31:20;12258;-401008;The Goblet;
2023/10/18 14:33:14;763371;751113;The Goblet;
2023/10/18 14:34:33;928441;165070;The Goblet;
2023/10/18 14:43:00;10312115;9383674;Mist;
2023/10/18 14:46:51;993828;-9318287;Mist;
2023/10/18 14:48:20;10312115;9318287;Mist;
2023/10/18 15:24:05;1375792;-8936323;The Goblet;
2023/10/18 15:25:25;2067753;691961;The Goblet;
2023/10/18 15:26:46;10312115;8244362;Mist;
2023/10/18 15:27:25;10312065;-50;Mist;(Teleport to Limsa Lominsa Lower Decks)
2023/10/18 15:28:31;10312040;-25;Limsa Lominsa Upper Decks;(Teleport to Mist)
2023/10/18 15:30:39;993828;-9318212;Mist;

**Comment by AtmoOmen** [comment]
My fault, and I sincerely apologize for that!

I've been working on a new update these days and have rewritten the code logic for the multi character detection section and tested it to be fine in that. I will push an update as soon as possible and release the plugin file here. After that, you can choose loading it in the form of dev plugins as an alternative until the update is aproved!

**Comment by Sinpls** [comment]
Ah, no problem! Thanks for the quick reply. I love using this plugin so thanks for your hard work. Looking forward to the update. I'll move all my data out of the folder for now and clean the illegal transactions.

**Comment by AtmoOmen** [comment]
Hey, I've submitted the new update 1.3.0.0, and it is currently awaiting review. Due to it being a large update, it may take several days to be approved.

You can now download [the local file](https://github.com/AtmoOmen/CurrencyTracker/releases/tag/1.3.0.0), extract it, and add the path to the plugin folder in ```Settings - Experimental - Dev Plugin Locations``` before the approval.

Once the 1.3.0.0 version update is approved, I will contact you again. You can then delete the local files and continue using the official online repo. If no further issues related to this problem occur, I will close this Issue at that time!

**Comment by Sinpls** [comment]
Nice! I'll wait on the update then. Thanks for the quick replies and fix.

**Comment by AtmoOmen** [comment]
1.3.0.0 Update has been officially approved.
You can now update your plugin and have a test, if nothing wrong, you can close the issue, or I will close the issue 2d later.
