### ISSUE TITLE
[Issue] CurrencyTracker parsing to wrong character when swapping character

### ISSUE THREAD

**Issue by Sinpls** [AtmoOmen/CurrencyTracker#12]
Hi again, I see that the parsing issue itself has been fixed and thanks for that, but a new issue popped up.

CurrencyTracker is parsing to the wrong character when swapping characters. It's identifying the swapping as a teleport. After that 1 specific transaction, the tracker functions as intended. Is this intended or not?

I did the following steps to get the logs at the bottom:

1. log in on character 1
2. Perform a 2,500 deposit to retainer
3. log in on character 2
4. Perform a 5,000 deposit to retainer
5. log in on character 1 again
6. log in on character 2 again

Character 1 logs:
2023/10/27 11:59:18;3954539;3954539;Mist;
2023/10/27 12:01:13;3952039;-2500;Mist;(Exchange with Summoning Bell)
2023/10/27 12:02:42;360239;-3591800;Mist;(Teleport to The Goblet)
2023/10/27 12:04:06;3952039;3591800;Mist;
2023/10/27 12:05:18;355239;-3596800;Mist;(Teleport to The Goblet)

Character 2 logs:
2023/10/27 12:02:44;360239;360239;The Goblet;
2023/10/27 12:03:17;355239;-5000;The Goblet;(Exchange with Summoning Bell)
2023/10/27 12:04:04;3952039;3596800;The Goblet;(Teleport to Mist)
2023/10/27 12:05:20;355239;-3596800;The Goblet;

**Comment by AtmoOmen** [comment]
Not intended, my bad. I just found that I forgot to add the logic of clearing the current information to the Teleport module after character logout , so it was mistakenly judged as teleportation by the plugin. And this bug will be fixed in 1.3.0.2

PR: https://github.com/goatcorp/DalamudPluginsD17/pull/2788

**Comment by Sinpls** [comment]
Cool, thanks for the quick reply!

**Comment by AtmoOmen** [comment]
The 1.3.0.2 update have just been approved, and you can update to see whether the problem will occuer again.

**Comment by Sinpls** [comment]
Thanks for the update. I won't be near my PC the next 2 days but will let you know after.

**Comment by Sinpls** [comment]
Seems to be resolved. Thanks!
