### ISSUE TITLE
Previous month tracking disappeared

### ISSUE THREAD

**Issue by ArcaneInferno** [AtmoOmen/CurrencyTracker#14]
Hi,

I'm not sure if this there's a bug, but does the plugin only tracks the current month?

I installed the plugin a few days ago, the month just rolled over and I open up the plugin to see the information.
The few days of November the plugin was installed are all disappeared.

Thanks.

**Comment by AtmoOmen** [comment]
Definitely not. for this issue, I have a bit of speculation about what might have caused it.
User data is my bottom line, and I will not attempt to destroy user data
I will push an update asap to try to solve this issue.

**Comment by ArcaneInferno** [comment]
Yeah, I wouldn't see any reason why you'd delete user data that's been accumulating but for some reason the last few days of November I had it running all those data no longer exists. However, I close this issue and reopen again if it does happen again.
