### ISSUE TITLE
Add more backup options

### ISSUE THREAD

**Issue by jjspace** [AtmoOmen/CurrencyTracker#16]
1. Allow disabling backups completely
2. Allow setting the frequency, I do not do nearly enough that I need a backup every 30 minutes
3. Allow turning off the chat message, it's just spam and I don't need to see it clutter up my chat log

**Comment by AtmoOmen** [comment]
Thanks for reporting and suggesting! I will make the necessary adjustments to the default settings configuration by disabling Auto Save and changing the default backup interval from 30min to 60min.

Regarding the issue with the Notification in Chat checkbox, it seems to be broken in the current version. I will promptly release a new version to address this issue. In the meantime, you can manually fix the problem by navigating to '...\AppData\Roaming\XIVLauncher\pluginConfigs\CurrencyTracker.json.' Open the file and locate the line ' "AutoSaveMessage": true,' then change 'true' to 'false.' After making this modification, re-enable the plugin, and it should resolve the notifications issue.

As for the left:
![image](https://github.com/AtmoOmen/CurrencyTracker/assets/110901588/65f31e0c-49ca-4c14-ab92-47c9aaa93848)

**Comment by ArcaneInferno** [comment]
Just to add further to this, could you definite x number of days or copies the backup to hold?

Last thing I do not want want to do is figure out where all the free disk space has gone.

**Comment by AtmoOmen** [comment]
> Just to add further to this, could you definite x number of days or copies the backup to hold?
> 
> Last thing I do not want want to do is figure out where all the free disk space has gone.

Though the backup files won't occupy too much disk spaces, I totally understand your concern.

I could add a new option to allow the user to set a maximum limit on the number of backup files, perhaps with a default setting of 10, or a feature for automatic cleaning expiraed files after X days.

Thanks for suggestions~

**Comment by ArcaneInferno** [comment]
> > Just to add further to this, could you definite x number of days or copies the backup to hold?
> > Last thing I do not want want to do is figure out where all the free disk space has gone.
> 
> Though the backup files won't occupy too much disk spaces, I totally understand your concern.
> 
> I could add a new option to allow the user to set a maximum limit on the number of backup files, perhaps with a default setting of 10, or a feature for automatic cleaning expiraed files after X days.
> 
> Thanks for suggestions~

Yeah I understand the backup are not huge files but the number of files it could generates is a concern without any clean up mechanism.

For example, if the backup interval were left on default 30mins in a hypothetical scenario if the game were left running the number of files could generate is 48 files per day. In an year you're looking around 17,520 files.

Realistically that's not possible but in more realistic scenario 16 files a day (play for 8 hours) and you login to the game for 275 days out of 365 this still generate around 4,400 files which doesn't get cleaned up.

**Comment by AtmoOmen** [comment]
1.3.2.5 version has been approved, you could now update in game at your earliest convenience.

**Comment by jjspace** [comment]
@AtmoOmen From a UX perspective I did not even know that `Backup` button was supposed to have settings under it. I thought clicking it would immediately trigger a backup (because that's what the button says) so I never even tried it to see that dropdown you showed. It might be better to change it to "Backup settings" or just create a dedicated settings window with a Backup section. If I had seen this I probably wouldn't have opened the issue in the first place.

On top of that text should not be used as a button or toggle. Even if I had discovered that dropdown I would not have thought to click the text that says "Auto backup" to toggle it. This should be a dedicated checkbox like you have for the chat message.

I will also second what @madness800 suggested. There should definitely be a way to limit how many backups it keeps either by number or by date. Most of the time someone would need a backup is to restore from a crash or corrupt data and I assume that wouldn't need a backup that's older than a week or two. I definitely do not need every hour for months and months saved.

**Comment by AtmoOmen** [comment]
> @AtmoOmen From a UX perspective I did not even know that `Backup` button was supposed to have settings under it. I thought clicking it would immediately trigger a backup (because that's what the button says) so I never even tried it to see that dropdown you showed. It might be better to change it to "Backup settings" or just create a dedicated settings window with a Backup section. If I had seen this I probably wouldn't have opened the issue in the first place.
> 
> On top of that text should not be used as a button or toggle. Even if I had discovered that dropdown I would not have thought to click the text that says "Auto backup" to toggle it. This should be a dedicated checkbox like you have for the chat message.
> 
> I will also second what @madness800 suggested. There should definitely be a way to limit how many backups it keeps either by number or by date. Most of the time someone would need a backup is to restore from a crash or corrupt data and I assume that wouldn't need a backup that's older than a week or two. I definitely do not need every hour for months and months saved.

The main reason for this design is to maintain consistency: all icon buttons with text will open a popup or an independent window when clicked, which is logically consistent in interaction design.
As for why the regular automatic backup function needs to be added, it's just because someone needs it and I think the demand is reasonable, so I added it.
As for toggling by clicking on text, I will consider redesigning it.

Finally, thanks for your detailed suggestions and explanations!
