### ISSUE TITLE
Export filename text box loses focus each time the default filename changes

### ISSUE THREAD

**Issue by noelneedsanap** [AtmoOmen/CurrencyTracker#21]
Whenever the default filename changes (so once a second), the filename entry box loses focus making it very difficult to type a filename and possible for an export attempt to fail even just hitting enter in the box with the wrong timing.

**Comment by AtmoOmen** [comment]
Thanks for reporting this! This issue will be fixed in the next version update that is pending approval! (https://github.com/goatcorp/DalamudPluginsD17/pull/3172)
