### ISSUE TITLE
Is there any way to remove characters from Multi-Chara Stats?

### ISSUE THREAD

**Issue by noelneedsanap** [AtmoOmen/CurrencyTracker#23]
I've made a few of one-off dummy alts for visiting other DCs and various tasks, and even though I've deleted their folders, they still show in Multi-Chara Stats which is limiting its usefulness. Is there a way I can clear them from it?

**Comment by AtmoOmen** [comment]
Currently no, there was supposed to be one when this feature was introduced, but I forgot it.
Thanks for reminding me, and I will add it asap!

**Comment by noelneedsanap** [comment]
Thank you for all your work on this plugin, I get a lot of use out of it!

**Comment by AtmoOmen** [comment]
I have added the deletion function. Just right-clicked the entry in Multi-Chara Stats popup and you can see the button.
