### ISSUE TITLE
Gil transaction to NPC

### ISSUE THREAD

**Issue by ArcaneInferno** [AtmoOmen/CurrencyTracker#25]
Hi,

With the recent update the when I sell items to the NPC it now appears each item as a separate entry.

Is it possible you could add an option to enable the old behaviour where selling multiple items would only result in a single gil transaction line appear for the npc?

Many Thanks.

**Comment by AtmoOmen** [comment]
It sounds like the module Record (Special) Exchange Result is not enabled correctly, you can try to disable and then enable it again in Settings.
There're no changes to the related modules' logic for months.

**Comment by ArcaneInferno** [comment]
That seems to have fixed it.

Thanks for help!
