### ISSUE TITLE
Certain currencies are not retrieved (Japanese)

### ISSUE THREAD

**Issue by stoat33** [AtmoOmen/CurrencyTracker#26]
Probably occurs only in Japanese.
Data is not retrieved for all currency names containing “:”.

Example
アラガントームストーン:因果(Allagan Tomestone of Causality)
クラフタースクリップ:白貨(White Crafters' Scrip)

Can you please make the process so that it does not matter if the currency name contains “:”?
Sorry if this is a known issue.

**Comment by AtmoOmen** [comment]
Thanks for reporting this, and I will fix this issue in next version

**Comment by stoat33** [comment]
I'm sorry I closed it.
I have started getting it, but it does not seem to stay in the history.
Only one line of the amount currently held is displayed.
If there is a Change, it is not recorded.
At any given time only one line is displayed and the amount on that line is updated.

**Comment by AtmoOmen** [comment]
Please first try to rename the currency to name without invalid chars and see if this could work.

I'm currently busy with my work and also rewriting Currency Tracker now. Also we know that Dawntrail and Dalamud API 10 are on their way soon. So I might not be able to release an update for this before 7.0, or probably not even before the rewritten version out.

**Comment by stoat33** [comment]
I'm sorry to bother you when you're busy. I am in no hurry, so take care of yourself.
Currencies that do not contain “:” are fine.
The problem is that in Japanese it is used in Allagan Tomestone.
EN clients don't use “:” so it works fine.
Please give the first priority to yourself.Thanks again.

**Comment by AtmoOmen** [comment]
Should be fixed in the latest version 1.4.0.0
