### ISSUE TITLE
Transaction merging incorrectly modifies the total of the resulting record

### ISSUE THREAD

**Issue by VariableVixen** [AtmoOmen/CurrencyTracker#3]
On my Centurio Seals history, I had a value of 1344, then two records with a change of +20 each from the same area, where I'd killed a pair of A ranks. This gave me a record listing +20=1364 and a record listing +20=1384, which was the total number of seals I had. When I merged my transactions, the resulting record had a listed change of +40 (correct) but a total of 1404 (merged last total of 1384 _plus_ the prior record's change of +20), which immediately produced a new (erroneous) record listing a change of -20 in my current zone for a (correct) total of 1384.

**Comment by VariableVixen** [comment]
Example with White Crafter's Scrip: [before](https://github.com/AtmoOmen/CurrencyTracker/assets/8753564/81076eab-b4f3-4d62-a57c-b711e68786ab) and [after](https://github.com/AtmoOmen/CurrencyTracker/assets/8753564/61fc1c61-eb72-47e2-8c07-86b6aa27792d) clicking the merge button.

**Comment by AtmoOmen** [comment]
Thanks for report.
It's been identified that in some cases, the final Amount will be incorrectly adding the final Change, which leads to the issue. I have now added additional conditional logic in that part of the code. After testing this revised logic with 7 types of currencies, combining a total of 189 records, no similar issues have been observed again.

**Comment by VariableVixen** [comment]
Just checked and the fix is verified working in the currently live version!
