### ISSUE TITLE
Request: merge transactions with same DIRECTION of change

### ISSUE THREAD

**Issue by VariableVixen** [AtmoOmen/CurrencyTracker#5]
For example, at my GC HQ, I can turn in items to get seals and that's a positive change, and I can then - at the same time, after that - _spend_ seals if I'm near cap, which is a negative change. I'd like to be able to merge the pile of seal _increase_ transactions because I can dump upwards of twenty items at once if I've been running a lot of instances, but I still want to have a separate transaction record for spending the seals after that.

**Comment by AtmoOmen** [comment]
I get your words. The feature is actually not difficult to add, and I've completed that. However, I currently have a relatively small amount of test data that meets the test requirements. I will proceed with further testing before making a release with the feature!

**Comment by VariableVixen** [comment]
Looks to be working like a charm! One additional request: could a merge threshold of zero be treated as infinite, in order to more easily merge _all_ qualifying transaction records? I like to see the income/spending per-zone, basically. If not, that's fine too, I can just set the threshold to 999999999, it'd just be a convenience thing. Could probably check if the value is `0` and if so set it to `int.MaxValue` if you're willing to implement that.

**Comment by AtmoOmen** [comment]
Thanks for advice! And that would be implemented in next update I'm working hard these days!

**Comment by VariableVixen** [comment]
Awesome, much appreciated!
