### ISSUE TITLE
Missing Tracker: Ventures

### ISSUE THREAD

**Issue by Sinpls** [AtmoOmen/CurrencyTracker#6]
Hi, I'd love the addition of Ventures as a tracked currency. I was unable to find it under Custom Tracker

**Comment by AtmoOmen** [comment]
I'm pretty sure Venture is not specifically filtered by the plugin.
And I've just tried adding, deleting Venture as well creating some transactions under Venture and everything works fine.
Maybe an input issue?

**Comment by Sinpls** [comment]
Ah it was indeed an input error. The search input is case sensitive so it could not find it through 'venture' but 'Venture' worked. Thanks!

**Comment by AtmoOmen** [comment]
Since my game client is not in English, I forgot to make the search box case insensitive. Thanks for reminding me that.
And in the next update, I will make the search input case insensitive!

**Comment by AtmoOmen** [comment]
Now in the lastest update, the serach filter input has been case insensitive!
