### ISSUE TITLE
Pagination buttons broken in the UI when below a certain width

### ISSUE THREAD

**Issue by VariableVixen** [AtmoOmen/CurrencyTracker#7]
The way the [pagination buttons](https://github.com/AtmoOmen/CurrencyTracker/assets/8753564/a3f900d1-c8ed-4f8e-92b7-f177ce7f92d7) are positioned from the _right_ edge of the window means that when the window is below a certain width, they [overlap with the records-per-page and graphs buttons](https://github.com/AtmoOmen/CurrencyTracker/assets/8753564/d68a59de-5000-4c4d-954d-f6dd732b4c54).

**Comment by AtmoOmen** [comment]
To be honest, this is an issue with IMGUI, as it does not provide native center alignment functionality. Therefore, the "center alignment" in the plugin is through calculating pos to roughly position the page flipping buttons in the middle, while the "Records Per Page" and "Graphs" buttons are just commonly left aligned, resulting in overlap.
I will try some methods to improve this issue, but it may not be able to fundamentally solve the problem..

**Comment by VariableVixen** [comment]
You could also just set window size constraints so the window can't be shrunk enough for it to matter, if that's easier

**Comment by AtmoOmen** [comment]
Thanks for advice but set a min size of the window may not be a good way for it have to think about different PC/Laptop screen size/font size, and I just put the Graphs button next to the paging component so now they would not overlap.
