### ISSUE TITLE
Transaction merging with a threshold of 0 doesn't work

### ISSUE THREAD

**Issue by VariableVixen** [AtmoOmen/CurrencyTracker#8]
At least for one-way merges (didn't test two-way), pressing the button with a threshold of `0` still produces the `Please enter a threshold` error message.

**Comment by AtmoOmen** [comment]
My fault, I only change the code logic of Two-Way Merge (Orig.), and I will fix that in the next update!
![image](https://github.com/AtmoOmen/CurrencyTracker/assets/110901588/264faf5a-3228-4c97-a822-94078815c94d)
