### ISSUE TITLE
Tasks For The Future / Identified Issues

### ISSUE THREAD

**Issue by AtmoOmen** [AtmoOmen/CurrencyTracker#9]
## Functionality

- [x] 1. Support exporting data files in Markdown syntax.
- [x] 2. Support copying transactions in .csv format.
- [ ] 3. Allow complete editing of every part of transactions
- [ ] 4. Allow transactions data insertion.
- [x] 5. Allow importing transactions data in the form of .csv or .md format/files.
- [ ] 6. Allow including retainers/saddle bags' item counts
- [x] 7. Allow ignoring teleporting fees.
- [x] 8. Fully support Gold Sacuer related features.
- [x] 9. Support record Trade target in your note

## Performance

- [ ] 1. Improve the current performance issues on the transactions page (pagination caching).

## Operations

- [x] 1. Refine the multi-selection operations on transactions when holding the Ctrl key.
- [x] 2. Improve the logic for clearing the current selection status.

## Code

- [x] 1. Refactor the current Main.cs to alleviate its bloated code situation.
- [x] 2. Rewrite the code logic currently left for converting early record data to current record data, allowing it to exist in another form.

**Comment by AtmoOmen** [comment]
2023.10.10
Finished refining the multi-selection operations on transactions when holding the Ctrl key.

**Comment by wkewinw** [comment]
Hey ^^ there is stuttering like a steady heartbeat with this plugin enabled.
EDIT: is there anything users can do for now to maybe make it better/stutter less?

**Comment by AtmoOmen** [comment]
Hey, if you are using Timer Mode now, you can try switching to Chat Mode in Track Mode, you can also delete the currencies that are not in your demand. That should improve.

But I would like to say that the performance cost of this plugin is not obivious in almost all cases and maybe you need to check other aspects/things to better deal with that!

**Comment by wkewinw** [comment]
> Hey, if you are using Timer Mode now, you can try switching to Chat Mode in Track Mode, you can also delete the currencies that are not in your demand. That should improve.
> 
> But I would like to say that the performance cost of this plugin is not obivious in almost all cases and maybe you need to check other aspects/things to better deal with that!

oooh my bad xD it was indeed the "Time Mode" that was causing my game to have quick stutters every 0.5 sec. many thanks for making the plugin! :D

**Comment by AtmoOmen** [comment]
2023.10.14 1.2.5.0
Finished:
 1. Support exporting data files in Markdown syntax.
 2. Support copying transactions in .csv format.
 5. Allow importing transactions data in the form of .csv or .md format/files.
 1. Refine the multi-selection operations on transactions when holding the Ctrl key.
 2. Improve the logic for clearing the current selection status.
 2. Rewrite the code logic currently left for converting early record data to current record data, allowing it to exist in another form.
